[build]
  command = "pip install -r requirements.txt"
  publish = "static" # المجلد الذي يحتوي على ملفات الـ CSS/JS والصور الثابتة

[functions]
  external_node_modules = []
  included_files = ["*.py", "games_package/**", "static/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
