[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[functions]
  included_files = ["*.py", "games_package/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
